

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./style/header.css";
import "./style/headermobile.css";
import "./style/dashboard.css";
import "./style/contact.css";
import React from "react";
import { ChevronDown } from "lucide-react";
import Navbar from "./nav/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* header */}
          <Navbar />
        {/* main page */}
        <div className="w-full ">
          {children}
        </div>
      </body>
    </html>
  );
}
